# Theme
title: 神神叨叨
#Navigation
Menu:
  主页: /
  时间轴: /archives
  标签: /tags
  关于: /about

#Post date format
date_format: YY年MM月DD日
#Read more
read_more:  阅读更多
#Plugins setting
highlight:
  enable: true
  theme: vs2015 #reference: source => plugins => highlight => styles=> style name
# https://busuanzi.ibruce.info/
busuanzi:
  enable: true
